[package]
name = "manga-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
iced = { version = "0.9.0", features = ["tokio", "image"] }
native-dialog = "0.6.4"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
tokio = { version = "1.29.1", features = ["fs"] }
zip = "0.6.6"
